from langchain_google_genai import ChatGoogleGenerativeAI

def get_answer(context: str, query: str, api_key: str) -> str:
    """
    Takes context from vectorstore, a user query, and an API key,
    and returns an answer generated by Google Gemini.
    """
    llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-flash",
        temperature=0,
        google_api_key=api_key
    )
    
    prompt = f"""
    You are a helpful assistant. Use the following retrieved context to answer the user's question.
    If you don't know the answer based on the context, just say that you don't know. 
    Do not make up information.
    
    Context:
    {context}
    
    Question:
    {query}
    
    Answer:
    """
    
    response = llm.invoke(prompt)
    return response.content
